=== kjburns/traffic-simulation/xml/vehicle-types.xsd
<?xml version="1.0" ?>
<?xml-stylesheet type="text/xsl" href="./xs3p-master/xs3p.xsl" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation>Schema for vehicle types file. This file describes vehicle types and vehicle groups.</xs:documentation>
    </xs:annotation>
    <xs:simpleType name="uuid">
        <xs:annotation>
            <xs:documentation>Universally unique identifier.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}" />
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="vehicle-types-and-groups">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="types">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="vehicle-type" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence />
                                    <xs:attribute name="name" type="xs:string" default="" />
                                    <xs:attribute name="uuid" type="uuid" use="required" />
                                    <xs:attribute name="models" type="uuid" use="required" />
                                    <xs:attribute name="colors" type="uuid" use="required" />
                                    <xs:attribute name="acceleration" type="uuid" use="required" />
                                    <xs:attribute name="deceleration" type="uuid" use="required" />
                                    <xs:attribute name="occupancy" type="uuid" use="required" />
                                    <xs:attribute name="sharing" default="none">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:enumeration value="transit" />
                                                <xs:enumeration value="hov" />
                                                <xs:enumeration value="none" />
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:anyAttribute processContents="skip" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="groups">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="group" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="vehicle" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence />
                                                <xs:attribute name="type" type="uuid" use="required" />
                                                <xs:anyAttribute processContents="skip" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="name" type="xs:string" default="" />
                                    <xs:attribute name="uuid" type="uuid" use="required" />
                                    <xs:anyAttribute processContents="skip" />
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:anyAttribute processContents="skip" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="version" type="xs:integer" use="required" />
            <xs:anyAttribute processContents="skip" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== kjburns/traffic-simulation/default-files/default.vehicle-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<vehicle-types-and-groups version="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                          xsi:noNamespaceSchemaLocation="../xml/vehicle-types.xsd">
    <types>
        <vehicle-type uuid="08ca86bd-88a4-4eef-b034-6303d02573fa"
                      models="4e0612c9-5863-48bd-a172-886ddc6afe3a"
                      colors="52436322-756d-4080-904f-bcb66cdf467c"
                      acceleration="16cab362-3de3-462f-b117-7238ec56199b"
                      deceleration="4572b89f-2414-4b5c-860c-1dc1dab3c64c"
                      occupancy="8f77c2f0-c78e-4fcc-a74f-f5e567d81d55"
                      name="Passenger Cars" />
        <vehicle-type uuid="ffa4d45f-35c0-4766-8aba-e3150d50eaf0"
                      models="83bcc985-eac5-4532-bd22-5f42a3768cac" 
                      colors="52436322-756d-4080-904f-bcb66cdf467c" 
                      acceleration="6ac2aa3f-990d-4e6a-aead-bfd9142ed490" 
                      deceleration="1c01e0e7-e3e1-4ee9-a142-94c61006b2b6"
                      occupancy="8f77c2f0-c78e-4fcc-a74f-f5e567d81d55"
                      name="Single Unit Trucks" />
        <vehicle-type uuid="7fdc0d76-615a-4224-87e8-476014266b3f"
                      models="fb388d5f-63cd-4960-a719-60b1ea10ea30"
                      colors="52436322-756d-4080-904f-bcb66cdf467c"
                      acceleration="80764b12-c76b-4bab-b05c-7223fe066bf3"
                      deceleration="1c01e0e7-e3e1-4ee9-a142-94c61006b2b6"
                      occupancy="8f77c2f0-c78e-4fcc-a74f-f5e567d81d55"
                      name="Semi-Trucks" />
    </types>
    <groups>
        <group uuid="39e0f52f-0a34-46be-afc9-9c3c345fe8e4" name="All Vehicles">
            <vehicle type="08ca86bd-88a4-4eef-b034-6303d02573fa" />
            <vehicle type="ffa4d45f-35c0-4766-8aba-e3150d50eaf0" />
            <vehicle type="7fdc0d76-615a-4224-87e8-476014266b3f" />
        </group>
        <group uuid="a7d4b81a-eec8-4a45-93e7-45390343a994" name="Passenger Cars" >
            <vehicle type="08ca86bd-88a4-4eef-b034-6303d02573fa" />
        </group>
        <group uuid="26f12b3b-3c07-4b95-a9ac-63195d6d1b41" name="Heavy Vehicles">
            <vehicle type="ffa4d45f-35c0-4766-8aba-e3150d50eaf0" />
            <vehicle type="7fdc0d76-615a-4224-87e8-476014266b3f" />
        </group>
    </groups>
</vehicle-types-and-groups>
